###
GET http://localhost:8080/review

###
POST http://localhost:8080/review/new
content-type: application/json

{
    "target": "David",
    "reviewers": [
        "Alice",
        "Bob",
        "Cathy"
    ]
}

### get pending review list
GET http://localhost:8080/feedback/pending

### get pending feedback by user
GET http://localhost:8080/feedback/pending/Alice

### get pending feedback by user (should be none)
GET http://localhost:8080/feedback/pending/Bob
